In [1]:
import pandas as pd

In [2]:
file_path = '/workspaces/demo-devcontainer-main/resource/holding-001.csv'

df = pd.read_csv(file_path, nrows=1000000)

In [3]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [4]:
df.groupby(['portno']).size()

portno
2998623    351
2998638     77
2998809     70
2998821     54
2999052      2
          ...
309260a      2
309260d    514
3092616      1
3092619    403
3092652     27
Length: 3867, dtype: int64

In [5]:
# sum of specific column
df.groupby(['portno'])['nbr_shares'].sum()

portno
2998623    3.817768e+09
2998638    4.856478e+08
2998809    1.312320e+08
2998821    7.659816e+07
2999052    8.600000e+05
               ...
309260a    5.265000e+06
309260d   -1.411982e+10
3092616    3.198600e+04
3092619    5.315248e+06
3092652    1.346848e+08
Name: nbr_shares, Length: 3867, dtype: float64

In [7]:
# show specific group
df.groupby('portno').get_group('2998623')

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
346,2998623,2020/11/30,352,2021/01/08,0.00,1303.0,1.594570e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10

In [8]:
# multi-value group by
"""
select portno,
    percent_tna,
    count(1)
from table
group by portno, percent_tna
"""

df.groupby(['portno', 'percent_tna']).size()

portno   percent_tna
2998623  -0.34           1
         -0.17           1
         -0.02           1
          0.00          19
          0.01           8
                        ..
3092652   0.61           3
          0.62           1
          0.63           1
          3.01           1
          101.93         1
Length: 184136, dtype: int64

In [9]:
# sort value
df.groupby(['portno', 'percent_tna']).sum().sort_values('percent_tna', ascending = False)

,,report_dt,security_rank,eff_dt,nbr_shares,market_val,security_name,cusip
portno,percent_tna,,,,,,,
308655c,300.08,2020/12/31,1,2021/01/08,8.666786e+07,8.666786e+07,Other Assets less Liabilities,0
3086562,300.04,2020/12/31,1,2021/01/08,1.588645e+08,1.588645e+08,Other Assets less Liabilities,0
3086607,300.01,2020/12/31,1,2021/01/08,2.904950e+08,2.904950e+08,Other Assets less Liabilities,0
3086604,299.94,2020/12/31,1,2021/01/08,7.105212e+07,7.105212e+07,Other Assets less Liabilities,0
3086556,299.85,2020/12/31,1,2021/01/08,6.097380e+07,6.097380e+07,Other Assets less Liabilities,0
...,...,...,...,...,...,...,...,...
3069606,-173.40,2020/11/30,660,2021/01/08,-5.910000e+03,-1.305233e+09,2YR T-NOTES MAR1,0
307545c,-176.40,2020/11/30,535,2021/01/08,-3.740000e+02,-8.259848e+07,2YR T-NOTES MAR1,0
3087462,-197.20,2020/11/30,4,2021/01/08,-5.900000e+03,-2.137688e+07,EMINI S&P DEC0,0
3086604,-199.90,2020/12/31,2,2021/01/08,-4.889844e+09,-4.736340e+07,JPY/USD Forward Contract,0
3086562,-200.00,2020/12/31,2,2021/01/08,-8.667746e+07,-1.059169e+08,EUR/USD Forward Contract,0